### ISSUE TITLE
Cannot Blacklist Vanilla Block

### ISSUE THREAD

**Issue by ardissaps** [Andrew6rant/InventoryTabs#28]
![image](https://user-images.githubusercontent.com/82106625/176821202-b090058d-2d6d-4b94-aedd-d09b70dcc026.png)
![image](https://user-images.githubusercontent.com/82106625/176821126-b7ff7d17-5abd-484d-b66c-3062535485b3.png)
![image](https://user-images.githubusercontent.com/82106625/176821243-f1df294c-753d-4700-99e4-9d4c3bd0a59c.png)

Wish could blacklist Loom while waiting for compatibility with [EasierCrafting](https://modrinth.com/mod/easiercrafting), but setting have no effect and the blacklist list reverted to default on restart.
Not in a hurry it is still fuction the button as not whole part overlapped. (Just minor aesthetic)
The compatibility request is on another [issue](https://github.com/Andrew6rant/InventoryTabs/issues/15#issuecomment-1164007016), this page for the [blacklist](https://user-images.githubusercontent.com/82106625/176821202-b090058d-2d6d-4b94-aedd-d09b70dcc026.png) that does not work.

**Comment by itsMarkiS** [comment]
UP!! im also trying to disable vanilla blocks, but im trying to disable single and double trapped chests / normal chests...

**Comment by ardissaps** [comment]
@Andrew6rant no matter how many times we add blacklist, the setting always revert to default.
![image](https://user-images.githubusercontent.com/82106625/177007970-969abb4b-d101-4b42-be9c-efbf87f55ad9.png)
These are every piece of fluid tank from [CreateFabric](https://modrinth.com/mod/create-fabric) and every piece of pipe from [Modern Dynamic](https://modrinth.com/mod/modern-dynamics), that actually does not have GUI by itself. And when we press those tab it place any block from highlighted hotbar from hand.

**Comment by MScott7** [comment]
I believe I'm also having the issue of my config reverting to default.

**Comment by Andrew6rant** [comment]
I've been wracking my head over this for a really long time, and it turns out the JSON serializer I used does not support empty Lists. I've always use GsonConfigSerializer for my configs, but this mod is one I picked up from a previous developer who was using JanksonConfigSerializer (JSON5).

This should be fixed in the next update, but your config will be reset to a different file (.json instead of .json5)

**Comment by Andrew6rant** [comment]
This is fixed in version 0.8.0. I am still going to leave this issue open because you currently are unable to blacklist blocks with custom TabProviders (Chests, Crafting table, etc). Every other modded and vanilla block should be able to be blacklisted

**Comment by itsMarkiS** [comment]
Im using 0.8.0
the blacklist doesnt reset anymore. its fixed
BUT... disabling vanilla blocks still doesnt works..

**Comment by RichPrune** [comment]
how do i blacklist modded blocks?????
